### ISSUE TITLE
Consider opening up access to dataset

### ISSUE THREAD

**Issue by I-Dont-Remember** [cmoog/traderjoes#5]
I'm not much of a data whiz myself, but there's a lot of really smart people who can do really interesting things when they get access to an open set of data. There's a lot of ways you could approach it if you wanted to do it, with varying complexity. Some ideas:

- Occasionally when it's convenient, add a snapshot of the DB to this repo
- Push a version to a static hosting site when your cron job finishes
- This seems like more effort to set up, but is kinda neat https://phiresky.github.io/blog/2021/hosting-sqlite-databases-on-github-pages/
- There was a tool posted on HN at one point that let you share SQLite DBs in the browser, but can't remember the name of it.
- ... a million other ways i'm sure you're aware of

Definitely not required, so do what makes the most sense for you with this project. It's great, thanks for sharing it!

**Comment by I-Dont-Remember** [comment]
And I jumped the gun, looks like you just updated the site to have a link to the `csv`. 😆

**Comment by cmoog** [comment]
Yup, agreed. Given that the whole dataset is one table, I think distributing the dump as a csv makes the most sense. Accessibility wise, I think it's far easier for a sqlite user to import a csv than it is for a nonsqlite user to extract the csv.
